### DISCUSSION TITLE
How can you specify the specification for array elements without a struct wrapper?

### DISCUSSION THREAD

**Discussion by cardilloscreations** [swaggo/swag#2033] [Q&A]
For a post body request, if the body is an array of UUID for example, and I don't want to wrap it in a struct, I can't find a way to provide the `format` specification for the array elements or the array `min` & `max`.

If I define it the way I want to, I can't find a way to add the additional `format`, `min`, `max` specifications:
```
type FinderEventID uuid.UUID

//	@Param			request	body		[]FinderEventID								true	"Finder event refs"
```

Of course, this produces a standard Swagger definition for an array of `string`, which I can hand edit to get the desired outcome, but I can't figure out a way to make swag do this properly.

What I really want to specify is that the request body must be an array [1..20] of UUID strings.

Desired JSON Request Body:
```
[
  "11111111-1111-1111-1111-111111111111"
]
```

-----

If I wrap it in a struct, then I can add the additional specifications, but the resulting JSON has more layers than is needed, and for no good reason.
```
type FinderEventID struct {
	EventID uuid.UUID `json:"eventID" validate:"required" format:"uuid" example:"[\"11111111-1111-1111-1111-111111111111\"]"`
}

type FinderEventRequest struct {
	Requests []FinderEventID `json:"requests" validate:"required,min=1,max=20"`
}
```
Swagger Definition:
```
    v1.FinderEventID:
      properties:
        eventID:
          example: 11111111-1111-1111-1111-111111111111
          format: uuid
          type: string
      required:
      - eventID
      type: object
    v1.FinderEventRequest:
      properties:
        requests:
          items:
            $ref: '#/components/schemas/v1.FinderEventID'
          maxItems: 20
          minItems: 1
          type: array
          uniqueItems: false
      required:
      - requests
      type: object
```
Example JSON Request Body:
```
{
  "requests": [
    {
      "eventID": "11111111-1111-1111-1111-111111111111"
    }
  ]
}
```

**Comment by cardilloscreations** [comment]
One step closer, only slightly better, but still not satisfying.

```
type FinderEventRequest struct {
	Events []uuid.UUID `json:"events" validate:"required,min=1,max=20" format:"uuid"`
}
```

Produces This Swagger Definition:
```
    v1.FinderEventRequest:
      properties:
        events:
          items:
            format: uuid
            type: string
          maxItems: 20
          minItems: 1
          type: array
          uniqueItems: false
      required:
      - events
      type: object
```

Example JSON Request Body:
```
{
  "events": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ]
}
```
