### ISSUE TITLE
Body parameter should support plaintext

### ISSUE THREAD

**Issue by jrschumacher** [swaggo/swag#1020]
**Describe the bug**
When using body parameter and the content type is `text/plain` the parameter `schema.type` should be `string` per [spec](https://github.com/swaggo/swag/blob/9fb19d0a36ed06a9d9b82e65322c7e1dbf143004/operation.go#L315-L320)

**To Reproduce**

```
// Generate Bisac and Keywords
// @Summary Plain text process
// @Description Plain text process
// @Param text body string true "Text to process"
// @Accept text/plain
// @Router /process [post]
```

**Expected behavior**

```
paths:
  /process:
    post:
      consumes:
      - plain/text
      description: Plain text process
      parameters:
      - description: Text to process
        in: body
        name: text
        required: true
        schema:
          type: string
```

**Your swag version**
v1.7.3

**Your go version**
v1.17.1
