### ISSUE TITLE
How can I add an example to the "[]map[string]interface{}" struct?

### ISSUE THREAD

**Issue by yukanke-saab** [swaggo/swag#1105]
https://github.com/swaggo/swag/issues/327
I saw this issue and learned how to add an example to "map[string]interface{}", but how do I add an example to "[]map[string]interface{}"?

I would like to output an example like the following.
```
"attachments": [
    {
      "title": "string",
      "path": "string"
    }
  ],
```

**Comment by ubogdan** [comment]
Have you tried the last example? 
``` 
CustomType map[string]interface{} `json:"map_data" swaggertype:"object,string" example:"key:value,key2:value2"` 
```

**Comment by yukanke-saab** [comment]
@ubogdan 
Of course.
But this was not what I wanted.

[Definition output by that sample]
```
        map_data:
          additionalProperties:
            type: string
          example:
            key: value
            key2: value
          type: object
```
[Definition I want to output]
```
        map_data:
          additionalProperties:
            type: string
          example:
            - key: value
              key2: value
          type: object
```
