### ISSUE TITLE
Wrong formating for custom struct names

### ISSUE THREAD

**Issue by F0rzend** [swaggo/swag#1150]
**Wrong formating for custom struct names**
When run `swag fmt` 2 spaces appear between `@name` and the name instead of one and the name is treated as an empty string

**To Reproduce**
1. Write a struct, for example
```go
type User struct {
	ID       uint   `json:"id"`
	Username string `json:"username"`
} // @name User
```
2. Run `swag fmt -g filename.go`
3. Get `@name  User` instead of `@name User` in your code
4. Run `swag init -g path/to/mani.go`
5. In docs/swagger.yaml you will see
```yaml
definitions:
  "":
    description: User information
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
```

**Expected behavior**
Correct type name, "User"

**Screenshots**
![image](https://user-images.githubusercontent.com/50886859/155784641-86b0c7dc-2d74-4372-a70c-ff311ca5ed7e.png)

**Swag version**
```sh
$ swag -v
swag version v1.8.0
```

**Go version**
```sh
$ go version
go version go1.18beta1 linux/amd64
```

**Desktop:**
 - OS: OS: Ubuntu 21.10 x86_64 
 - Browser: Firefox browser 97.0 (64-bit); Mozila Firefox for Ubuntu canonical - 1.0
 - Version: 21.10
