### ISSUE TITLE
Question: define optional authorization in an enpoint

### ISSUE THREAD

**Issue by ayoubfaouzi** [swaggo/swag#1226]
Hello,

In OA, we can use something like this to define optional security:

```yml
security:
  - {}   # <----
  - api_key: []
 ```

This means the endpoint can be called with or without security.

My question is how can I enable the same thing using with `swag`.

I attempted this code but it produces slightly different yml.

```go
// @Security ApiKeyAuth || {}
```

```yml
  security:
  - '{}': []
    ApiKeyAuth: []
```

Cheers.
