### ISSUE TITLE
Struct field comments get incorrectly duplicated when using type aliases from other packages

### ISSUE THREAD

**Issue by djui** [swaggo/swag#1342]
**Describe the bug**

When using a comment on a struct field with a type alias to another package which also gets replaced, this field's comment will be duplicated to other fields that should not have a comment (or their own comment).

**To Reproduce**
This examples will demonstrate the issue: See in the `swagger.yaml` the field `b` has a description (`Comment`) but shouldn't.

```go
// main.go

package main

import (
	"database/sql"
	"net/http"
)

type Bool sql.NullBool

type Foo struct {
	A Bool // Comment
	B Bool
}

// @Success 200 {object} Foo
func handle(w http.ResponseWriter, r *http.Request) {}
```

```
# .swaggo
replace database/sql.NullBool boolean
```

Run: 
```sh
swag init --parseDependency --overridesFile ".swaggo" --dir cmd/main --outputTypes yaml
```

Output: 
```yaml
# swagger.yaml
main.Foo:
  properties:
    a:
      description: Comment
      type: boolean
    b:
      description: Comment
      type: boolean
  type: object
```

**Expected behavior**

**Screenshots**
-

**Your swag version**
e.g. 1.8.6

**Your go version**
e.g. 1.19.1

**Desktop (please complete the following information):**
 - OS: MacOS 12.6

**Additional context**
-
