### ISSUE TITLE
github.com/[Path to Project]/docs: no matching versions for query "latest"

### ISSUE THREAD

**Issue by yusrilmr** [swaggo/swag#1358]
**Describe the bug**
Apparently, there is an issue when setting up the Host programmatically.

It happens in GitHub action.
After executing `go install github.com/swaggo/swag/cmd/swag@latest`. Then, execute `go mod tidy`.
It smh shows:
```
github.com/[Path to Project]/docs: no matching versions for query "latest"
```

I suspect the problem is related to this:
```
docs.SwaggerInfo.Host = ...
```
I set the host programmatically, and it has been working just fine for months.
After this error occurs, I tried commenting this line of code then my GitHub action works again.

**To Reproduce**
1. Set your host programmatically in your code
```
docs.SwaggerInfo.Host = ...
```

2. Set your github workflow with the following setting(Some attributes are hidden to reduce complexity):
```
name: PR Workflow
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
env:
 ...
jobs:
  build-and-test:
    needs: feature-branch-name-check
    runs-on: ubuntu-latest
    # Add private GO repo
    env:
      ...
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout repo including the git submodules.
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ORCHESTRATOR_GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18' 
      - run: go version
...
      - name: Download
        run: go mod download
      - name: Download swaggo
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Download tidy
        run: go mod tidy
      - name: Generate swagger Docs
        run: swag init -g cmd/main.go --parseDependency
...
```
3. Create a PR to run the pipeline
4. See the error
<img width="786" alt="Screenshot 2022-10-24 at 17 19 03" src="https://user-images.githubusercontent.com/4738623/197563266-8d12a6de-a80b-4ef1-b82d-8f84e5d0018e.png">

**Expected behavior**
There should be no error

**Screenshots**
<img width="786" alt="Screenshot 2022-10-24 at 17 19 03" src="https://user-images.githubusercontent.com/4738623/197563266-8d12a6de-a80b-4ef1-b82d-8f84e5d0018e.png">

**Your swag version**
I tried with 
`go install github.com/swaggo/swag/cmd/swag@v1.8.3`
and
`go install github.com/swaggo/swag/cmd/swag@latest`
Both have the same issue.

**Your go version**
e.g. 1.18

**Desktop (please complete the following information):**
 - GitHub Action OS: `runs-on: ubuntu-latest`
