### ISSUE TITLE
Regression on 1.8.8 on security definition

### ISSUE THREAD

**Issue by rdelcorro** [swaggo/swag#1409]
On version 1.8.7 I am able to generate a security definition with this code

```
// @title                      DEMO
// @version                    1
// @host                       localhost:8080
// @securityDefinitions.apikey ApiKeyAuth
// @in                         header
// @name                       Authorization
// @description                Description

func main() {
	
}

```

```
securityDefinitions:
  ApiKeyAuth:
    description: Description
    in: header
    name: Authorization
    type: apiKey
```

In version 1.8.8 the rendered yaml removes the security definition using the exact same comments
