### ISSUE TITLE
Docs generations doesn't work

### ISSUE THREAD

**Issue by agustin-del-pino** [swaggo/swag#1433]
**Describe the bug**
I'm using a non-common scaffolding for my project. Where everything is separated by entities. With this, the entrypoint is in one place and the controller in another.

Something like this:
````yml
projectRoot:
  - cmd:
      - main.go
  - internal:
      - app:
          - infra:
             # The Routes declaration (Gin) And the general info declaration
              - routes.go 
          - app.go
      - entityFoo:
          - infra:
              - http:
                 # The controller of the route (Gin Handler)
                  - controller.go 
````

**To Reproduce**
1. Use ` swag init -g .\internal\server\infra\routes.go `.  Only parse that specific file. Of course because the controller doesn't belong to the "infra" module.
2. Use the `-d` to add the directory. `swag init -g .\internal\server\infra\routes.go -d .\internal\entityFoo\infra\http`
3. See the error
````
Generate swagger docs....
Generate general API Info, search dir:.\internal\entityFoo\infra\http\
cannot parse source files ~\internal\entityFoo\infra\http\internal\server\infra\routes.go: 
open ~\internal\entityFoo\infra\http\internal\server\infra\routes.go: The system cannot find the path specified.
````

**Expected behavior**
I expect the `swag` parses the `routes.go` as *General Info* and then parse the additional directory. 

**Your swag version**
**v1.8.9**

**Your go version**
**1.19**

**Desktop:**
 - Windows 10.

**Additional context**
I don't understand why `swag` concatenates the two paths.
But if I trick this like `swag init -g .\internal\server\infra\routes.go -d .\,.\internal\entityFoo\infra\http\`. 
It works only for the *General Info* but not for the Controller.
