### ISSUE TITLE
any being treated as object type

### ISSUE THREAD

**Issue by Ewocker** [swaggo/swag#1452]
**Describe the bug**
Golang type any today will be translate to `type: object` in schema

**To Reproduce**
Example
```
type Metadata struct {
	// description
	Metadata *map[string]any
}
```
is giving
```
metadata:
  additionalProperties: {}
  description: description
  type: object
```
while `object` does not mean any in golang

**Expected behavior**
Should instead give Any Value as described in here doc https://swagger.io/docs/specification/data-models/data-types/#any (for v2)

**Screenshots**

**Your swag version**
swag version v1.8.4

**Your go version**
go1.19.4

**Desktop (please complete the following information):**
 - OS: Mac Ios
 - Browser: chrome
