### ISSUE TITLE
Nested enum fields do not have deterministic generation

### ISSUE THREAD

**Issue by decentralgabe** [swaggo/swag#1587]
**Describe the bug**
I have an annotation as follows
```
//	@Success		201		{object}	CreateDIDByMethodResponse
```

where `CreateDIDByMethodResponse` is

```go
type CreateDIDByMethodResponse struct {
	DID didsdk.Document `json:"did,omitempty"`
}
```

The object `didsdk.Document` is from a library, and fairly complex. One of the fields nested in a property of `didsdk.Document` is an object...

```
	Type            cryptosuite.LDKeyType `json:"type" validate:"required"`
```

Swaggo seems to have trouble with this. Upon generation with the command

`swag init --pd --parseInternal -o doc -ot go,yaml`

it works; however, running the command again shows a git diff like

```
   cryptosuite.LDKeyType:
     enum:
-    - Bls12381G2Key2020
     - X25519KeyAgreementKey2020
     - Ed25519VerificationKey2020
     - X25519KeyAgreementKey2019
     - Ed25519VerificationKey2018
     - EcdsaSecp256k1VerificationKey2019
+    - Bls12381G2Key2020
     - JsonWebKey2020
     - JsonWebKey2020
     - Bls12381G2Key2020
     type: string
     x-enum-varnames:
-    - BBSPlusSignatureSuiteType
     - X25519KeyAgreementKey2020
     - Ed25519VerificationKey2020
     - X25519KeyAgreementKey2019
     - Ed25519VerificationKey2018
     - ECDSASECP256k1VerificationKey2019
+    - BBSPlusSignatureSuiteType
     - JSONWebKey2020Type
     - JWSSignatureSuiteType
     - BLS12381G2Key2020
```

on a second run I see

```
   cryptosuite.LDKeyType:
     enum:
-    - Bls12381G2Key2020
+    - JsonWebKey2020
     - X25519KeyAgreementKey2020
     - Ed25519VerificationKey2020
     - X25519KeyAgreementKey2019
     - Ed25519VerificationKey2018
     - EcdsaSecp256k1VerificationKey2019
-    - JsonWebKey2020
-    - JsonWebKey2020
     - Bls12381G2Key2020
+    - Bls12381G2Key2020
+    - JsonWebKey2020
     type: string
     x-enum-varnames:
-    - BBSPlusSignatureSuiteType
+    - JWSSignatureSuiteType
     - X25519KeyAgreementKey2020
     - Ed25519VerificationKey2020
     - X25519KeyAgreementKey2019
     - Ed25519VerificationKey2018
     - ECDSASECP256k1VerificationKey2019
-    - JWSSignatureSuiteType
-    - JSONWebKey2020Type
+    - BBSPlusSignatureSuiteType
     - BLS12381G2Key2020
+    - JSONWebKey2020Type
```

this makes it impossible to have a deterministic build.

**Your swag version**
2.0.0-rc3

**Your go version**
1.20.4

**Desktop (please complete the following information):**
latest macos using an m1 chip
