### ISSUE TITLE
Add minimum and maximum on parameters query

### ISSUE THREAD

**Issue by thang1160** [swaggo/swag#1609]
**Is your feature request related to a problem? Please describe.**
Here I have parameters with the `minimum` tag on it
```
  /domestic/config-approval:
    get:
      parameters:
      - in: query
        minimum: 0
        name: page
        type: integer
      - in: query
        minimum: 1
        name: pageSize
        type: integer
...
```
In the Swagger UI, it didn't show up but the validation still works making our automation tester team confused.

![Screenshot from 2023-06-21 16-41-30](https://github.com/swaggo/swag/assets/35557579/a6af75d1-b4b7-47f0-8566-f9db18f261ac)

The Swaggerhub implemented this long ago, so I don't see why it does not exist here.

![image](https://github.com/swaggo/swag/assets/35557579/7d65e3b0-557c-46c0-96a3-f3d79847ad22)

**Describe the solution you'd like**
Add minimum and maximum on parameters query
