### ISSUE TITLE
add pattern or example to string value in a model

### ISSUE THREAD

**Issue by jonathan-dev** [swaggo/swag#1776]
I there any  possibility to add pattern or example information like this
```
    properties:
      releaseDate:
        type: date
        pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
        example: "2019-05-17"
```
(https://stackoverflow.com/a/64035263/6938528)

And I also would be interested in setting the format mentioned [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#data-types)
