### ISSUE TITLE
Custom fields for tags

### ISSUE THREAD

**Issue by Ponywka** [swaggo/swag#1784]
**Is your feature request related to a problem? Please describe.**
I'm using [ReDoc](https://redocly.github.io/redoc/) to generate own documentation from OpenAPI specification. They have `x-displayName` parameter for tags.
Example:  [museum.yaml](https://redocly.github.io/redoc/museum.yaml)
```yaml
tags:
  - name: Operations
    x-displayName: About the museum
    description: Operational information about the museum.
```

**Describe the solution you'd like**
I want to got custom fields for tags like `// @tag.x-displayName This is very cool tag`

**Describe alternatives you've considered**
-

**Additional context**
-
