### ISSUE TITLE
field of `any` type behaves badly when specifying json field name

### ISSUE THREAD

**Issue by shomeax** [swaggo/swag#1833]
**Describe the bug**
swag fails to generate proper OpenAPI definition when field of `any` type is used simultaneously with `json` hint.
 

**To Reproduce**

for the following example structure:
```
type MyRequest struct {
	Name            string                   `json:"name" binding:"required,validName,max=200" example:"Bob"` // Name
	Value             any                       `json:"value" binding:"omitempty" example:"dunno"`                            // Arbitrary value
}

```

and following handler:
```
// @Summary Create Object
// @Tags Version v1.0.0
// @Produce json
// @Accept  json
// @Success 202 {object} MyResponse
// @Failure 400 {object} httpErrorsV0.BadRequest
// @Failure 401 {object} httpErrorsV0.UnauthorizedError
// @Failure 500 {object} httpErrorsV0.InternalServerError
// @Param  data body MyRequest true "New object parameters"
// @Router /v1/objects [POST]
// @description  Create object is async operation, it means that server returns 202 Accepted and continue work asynchronously.
func (handler *ObjectsHttpHandler) NewObject(context *gin.Context) {
...
}
```

Following swagger document is generated when I use `swag init --parseDependency`:

```
definitions:
  MyRequest:
    type: object
  MyResponse:
    properties:
       ...
paths:
  /v1/stands:
    get:
      ...
    post:
      consumes:
      - application/json
      description: |-
        Create object is async operation, it means that server returns 202 Accepted and continue work asynchronously.
      parameters:
      - description: New object parameters
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/MyRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/MyResponse'
...
```

Otherwise speaking, the whole object is squashed into blob without properties, bug.

**Expected behavior**
However, if I remove the `json: "value" ...` hint, e.g. for the following structure:

```
type MyRequest struct {
	Name            string                   `json:"name" binding:"required,validName,max=200" example:"Bob"` // Name
	Value             any                       // Arbitrary value
}

```

The result document is generated properly:

```
  MyRequest:
    properties:
      name:
        description: Name of object
        example: Bob
        maxLength: 200
        type: string
      ttl:
        description: Arbitrary object
    required:
    - name
    type: object
  MyResponse:
    properties:
       ...
```

**Your swag version**
swag@latest

**Your go version**
1.19.2
