### ISSUE TITLE
Duplicated values generating an enum from constants.

### ISSUE THREAD

**Issue by jorge-fuertes** [swaggo/swag#1888]
Swaggo generates duplicated values for an enum. From this code:

```go
const (
	En Language = "EN"
	De Language = "DE"
	Zh Language = "ZH"
	DefaultLanguage = En
)
```

The resulting enum description for any entity using `Language` is:

```yaml
  model.Language:
    enum:
    - EN
    - DE
    - ZH
    - EN  # Duplicated
    type: string
```

We will need something like an ignore tag for constants:

```go
const (
	En Language = "EN"
	De Language = "DE"
	Zh Language = "ZH"

	// @swaggerignore
	DefaultLanguage = En
)
```

Or just detect the duplicated values while doc generation.

I'll really appreciate that if you can take this into consideration. Thanks in advance.
