### ISSUE TITLE
Support for multiple servers.

### ISSUE THREAD

**Issue by lkobylski-s2g** [swaggo/swag#1952]
API Swagger allows us to define multiple main endpoints (hosts) for our documentation. This facilitates distinguishing between environments such as local, dev, prod. Is it possible to handle 'servers' configuration?

```
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
```
