### ISSUE TITLE
Generate a schema containing specific field with "additionalProperties": true 

### ISSUE THREAD

**Issue by huaqing1994** [swaggo/swag#1958]
Can I generate a schema like
```
"objectType": {
    "type": "object",
    "properties": {
        "field1": {
            "additionalProperties": true
        },
        "field2": {
            "additionalProperties": true
        }
    }
}
```
by swaggo from a golang struct ?

**Comment by sdghchj** [comment]
No way at present.

**Comment by sdghchj** [comment]
```
type objectType struct{
field1 map[string]interface{}
field2 map[string]interface{}
}
```

**Comment by empicano** [comment]
Piggybacking on this, is there a way to define a request body that's a combination of defined attributes and `additionalProperties: true`? Given that we can define `@param body` only once, I haven't found a way to do that.

```yml
ExampleObject:
  type: object
  required:
    - id
    - name
  properties:
    id:
      type: string
    name:
      type: string
  additionalProperties: true
```
