### ISSUE TITLE
x-servers

### ISSUE THREAD

**Issue by lfaoro** [swaggo/swag#200]
Is there a way to define x-servers?

```yaml
x-servers:
  - url: 'https://api.rebilly.com/v2.1'
    description: Live Server
  - url: 'https://api-sandbox.rebilly.com/v2.1'
    description: Sandbox Server
```
