### ISSUE TITLE
swaggo use structs field name instead of xml tag

### ISSUE THREAD

**Issue by jetuuuu** [swaggo/swag#427]
**Describe the bug**
Hi. Swaggo doesn't use structs xml tag when it generate a swagger.yml/swagger.json
I have a struct like this: 
```
type Data struct {
    Name string `xml:"name_field"`
    Photo int `xml:"super_photo_id"`
}
```
and my swagger.yml is wrong and include this:
```
  pkg.Data:
    properties:
      name:
        type: string
      photo:
        type: integer
    type: object
```
**Expected behavior**
```
  pkg.Data:
    properties:
      name_field:
        type: string
      super_photo_id:
        type: integer
    type: object
```

**Your swag version**
1.5.1

**Your go version**
1.12.5

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
