### ISSUE TITLE
Option for removing the generation time at top of docs.go

### ISSUE THREAD

**Issue by xizhibei** [swaggo/swag#488]
**Is your feature request related to a problem? Please describe.**
I add the `docs` dir to my git repo, and I want add the docs generation step to git pre commit hook for automation.

But every time the hook executes, the timestamp at the top of `docs.go` changes, even no changes in other parts of `docs.go`

**Describe the solution you'd like**
A cli option for removing the timestamp.

**Describe alternatives you've considered**
1. Check the `docs.go` changes, if the content is not change, then no for the timestamp too.
2. Completely remove the timestamp, since we can always get the doc modify time and author from git.

For 2, there are some other tools used for generation won't add timestamp at their generated text.

For examples:

1. https://github.com/golang/mock
2. https://github.com/go-kit/kit

**Additional context**
None.

**Comment by ubogdan** [comment]
If i understand well , your git pre commit hook should force the user to not be able to commit if the latest commited docs.go file is different from the one generated  via hook. Correct ?

**Comment by xizhibei** [comment]
Yes, and thanks for your reply.

I'm using the [pre-commit](https://pre-commit.com/) and it won't let me commit if the code is modified by the hooks, but it does not matter, what I am saying is the timestamp should not be added to git.

The hooks is simple:

```yaml
- repo: local
  hooks:
  - id: generate-docs
    name: Generate docs
    pass_filenames: false
    entry: swag init --generalInfo cmd/server.go
    files: \.go$
    language: system
    types: [text]
```
