### ISSUE TITLE
@Param array type support

### ISSUE THREAD

**Issue by victorKochkarev** [swaggo/swag#494]
At the current moment, there is no way to define @Param as array type.
For example 

`//@Param status query []string false "Status"`

that would result in following swagger json
```
{
  "type": "array",
  "items": {
    "type": "string"
  },
  "description": "Status",
  "name": "status",
  "in": "query"
}
```

and yaml

```
description: status
        in: query
        name: status
        type: array
        items:
          type: string
```
