### ISSUE TITLE
Use map nested in struct

### ISSUE THREAD

**Issue by lvandenbrink** [swaggo/swag#517]
**I would like to use a map in a object**
I have the following object:
```
type Bar struct {
	Field2 string
}
type FooBarMap struct {
	Field3  map[string]Bar
}
```

**Expected behavior**
I would like to result in the following swagger definition
```
FooBarMap:
    type: object
    properties:
      field3:
        type: object
        additionalProperties:
          type: object
          properties:
            field2:
              type: string

```

**Swag version**
v1.6.2

**Go version**
go version go1.12.5 linux/amd64
