### ISSUE TITLE
How to Add multiple Headers

### ISSUE THREAD

**Issue by xiaoxfan** [swaggo/swag#519]
### Is there any way to add multiple headers?
I use the code below,but it support only one header attribute.
I need to add other attributes(not for authorization) in header,such as ClientID etc..how to do it, thanks .
```

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
```

**Comment by ubogdan** [comment]
I'm not going to ask you why since you should have that info after you check the authorization.
Is this request an Open API 2.0 compliant?

**Comment by erichll** [comment]
I'd like to know how to add Multiple API Keys.
[Multiple API Keys](https://swagger.io/docs/specification/authentication/api-keys/)

```yaml
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
    appId:
      type: apiKey
      in: header
      name: X-APP-ID
security:
  - apiKey: []
    appId:  []   # <-- no leading dash (-)
```
