### ISSUE TITLE
Not detecting controller definitions using go-chi

### ISSUE THREAD

**Issue by wilian746** [swaggo/swag#719]
In my project i using [go-chi](https://github.com/go-chi/chi) but when i run command
`swag init`
but only the swagger base is generated. The implemented routes are not recognized
Can someone help me?

My project is here: [https://github.com/wilian746/go-generator/tree/feature/swagger/pkg/standart-gorm](https://github.com/wilian746/go-generator/tree/feature/swagger/pkg/standart-gorm)

My structure is:
```
  cmd:
    docs: //directory of docs generated using swag cli
    - main.go // main of project 
  internal: 
    routes:
      - routes.go // definitions of routes
    handlers:
      health:
        - health.go // input handler 
```

My swag is version: `swag version v1.6.6`

My golang is version: `go version go1.14.2 linux/amd64`
