### ISSUE TITLE
Add Default Parameter Values

### ISSUE THREAD

**Issue by pei0804** [swaggo/swag#81]
https://swagger.io/docs/specification/2-0/describing-parameters/

**Comment by pei0804** [comment]
```yaml
      parameters:
        - in: query
          name: offset
          type: integer
          required: false
          default: 0
          minimum: 0
          description: The number of items to skip before starting to collect the result set.
```
