### ISSUE TITLE
Add Validation(max, min)

### ISSUE THREAD

**Issue by pei0804** [swaggo/swag#82]
https://swagger.io/docs/specification/2-0/describing-parameters/
```yaml
        - in: query
          name: limit
          type: integer
          required: false
          default: 20
          minimum: 1 <--
          maximum: 100 <--
          description: The numbers of items to return.
```
