### ISSUE TITLE
Add Array and Multi-Value Parameters

### ISSUE THREAD

**Issue by pei0804** [swaggo/swag#83]
https://swagger.io/docs/specification/2-0/describing-parameters/

```yaml
      # color=red,black,white
      parameters:
        - in: query
          name: color
          type: array
          collectionFormat: csv
          items:
            type: string
```

```
// @Param some_id []query true "Some ID" uniqueItems(true) minnux(0)
```
