### ISSUE TITLE
Incorrect parsing of sample string slices containing commas

### ISSUE THREAD

**Issue by shouhei** [swaggo/swag#899]
**Describe the bug**
Incorrect parsing of sample string slices containing commas.

**To Reproduce**

When I defined the following structure and generate swagger using `swag init`.

```go
type Example struct {
    Messages []string `json:"Messages" example:"\"a,b,c\",\"a,b,c\""`
}
```

Outputted  like this.

```yml
definitions:
  main.Example:
    properties:
      Messages:
        example:
        - '"a'
        - b
        - c"
        - '"a'
        - b
        - c"
        items:
          type: string
        type: array
    type: object
```

**Expected behavior**

I expect  to output like 

```yml
definitions:
  main.Example:
    properties:
      Messages:
        example:
        - "a,b,c"
        - "a,b,c"
        items:
          type: string
        type: array
    type: object
```

**Your swag version**
v1.6.9

---

I think, It will be able to fix by modify the code to use csv reader alternative to use strings.Split.

https://github.com/swaggo/swag/blob/master/parser.go#L1278
