### ISSUE TITLE
Enums support for array query parameters

### ISSUE THREAD

**Issue by j-sv** [swaggo/swag#918]
It would be useful to be able to set `enums` to describe valid values for an array query parameter. 

Example:
`@param field query []string "description" collectionFormat(csv) enums(foo,bar)`

This should generate the following:
```yaml
- description: description
  name: field
  in: query
  type: array
  collectionFormat: csv
  items:
    type: string
    enum:
      - foo
      - bar
```
Instead the code generation will put the `enum` field directly on the parameter field.

```yaml
- description: description
  name: field
  in: query
  type: array
  collectionFormat: csv
  items:
    type: string
  enum:
    - foo
    - bar
```

The enum values are then not displayed in the Swagger page.
