### ISSUE TITLE
Support query, path, header and formData param parse

### ISSUE THREAD

**Issue by amazing-gao** [swaggo/swag#931]
**Is your feature request related to a problem? Please describe.**
When I use `swag` to parse `gin` query param like this, `ActID` will be parsed to `actID` not form tag value `actId`.

```go
RedeemDownloadReq struct {
    ActID        int    `form:"actId" binding:"required"` // todo
    RedeemRuleID int    `form:"redeemRuleId"` // todo
}

// RedeemRuleDownload down redeem codes
// @Param data query RedeemDownloadReq true "data"
// @Success 200 {object} Response "TODO"
// @Failure 400 {object}Response "TODO"
// @Failure 500 {object}Response "TODO"
// @Router /redeemcode/download [get]
func (ctrl Controller) RedeemRuleDownload(ctx *gin.Context) {
	param := &RedeemDownloadReq{}
	if err := ctx.ShouldBindQuery(param); err != nil {
		ctrl.ReplyErrParam(ctx, "", err)
		return
	}
   ...
}
```

```yaml
      parameters:
      - description: todo
        in: query
        name: actID
        required: true
        type: integer
      - description: todo
        in: query
        name: redeemRuleID
        type: integer
```

**Describe the solution you'd like**
Support parse query, path, header, and formData tags.

**Describe alternatives you've considered**
Support plugin or parse handler for the user to custom parser.

**Additional context**
No
