### ISSUE TITLE
support use json tag as name on anonymous field

### ISSUE THREAD

**Issue by mzycynb** [swaggo/swag#943]
support use json tag name on anonymous field
example

```
type Foo struct {
    Bar string `json:"bar"`
}
type Example struct {
    Foo `json:"foo"`
    Case string `json:"case"`
}
```

should produce schema
```
example:
  type: object
  properties:
    foo:
      type: object
      properties:
        bar:
          type:
            string
    case:
      type:
        string
```

not
```
example:
  type: object
  properties:
    bar:
      type:
        string
    case:
      type:
        string
```
