### ISSUE TITLE
Support @x- attributes for security definition

### ISSUE THREAD

**Issue by pmorelli92** [swaggo/swag#970]
Seeing how was #452 done, can we get the same functionality for security definitions? 

I would need to generate this:

```
securityDefinitions:
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-audiences: "1234"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
```

But if I write the following code:

```
// @securitydefinitions.oauth2.implicit google_id_token
// @authorizationurl ""
// @x-google-audiences "1234"
// @x-google-issuer "https://accounts.google.com"
// @x-google-jwks_uri "https://www.googleapis.com/oauth2/v3/certs"
```

I get the following snippet where the `@x-attributes` are outside the security definition.

```
securityDefinitions:
  google_id_token:
    authorizationUrl: '""'
    flow: implicit
    type: oauth2
swagger: "2.0"
x-google-audiences: "1234"
x-google-issuer: https://accounts.google.com
x-google-jwks_uri: https://www.googleapis.com/oauth2/v3/certs
```

This should be valid according the `OpenAPI Extensions` document.
