### ISSUE TITLE
How to config Multiple API Keys

### ISSUE THREAD

**Issue by erichll** [swaggo/swag#977]
Some APIs use a pair of security keys, say, API Key and App ID. To specify that the keys are used together (as in logical AND), list them in the same array item in the security array:

in OAS3:

```yml
omponents:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
    appId:
      type: apiKey
      in: header
      name: X-APP-ID
security:
  - apiKey: []
    appId:  []   # <-- no leading dash (-)
```

in OAS2:

```yml

securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-API-KEY
  appId:
    type: apiKey
    in: header
    name: X-APP-ID
security:
  - apiKey: []
    appId: []
```

https://swagger.io/docs/specification/2-0/authentication/api-keys/

https://swagger.io/docs/specification/authentication/api-keys/
